version: "3.0"
services:
  mysql:
    container_name: mysql
    image: mysql:5
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env
    volumes:
      - '${MYSQL_DATA_DIR}:/var/lib/mysql'